security:
  clients:
    mobile:
      id: mobile
      secret: mobile
      role: USER
    web:
      id: web
      secret: web
      role: USER
    admin:
      id: admin
      secret: admin
      role: ADMIN

